Crud cliente 2
niver-copa/back-funval pull request #10
Opened 2023-08-31 19:21 UTC by myltonxdd

2023-08-31 20:02 UTC, herokudev requested changes

2023-08-31 20:02 UTC, herokudev commented on app/Http/Controllers/ClientesController.php
> +    public function create(Request $body)
No hay validacion de tipo de dato

2023-09-01 14:37 UTC, herokudev approved these changes

2023-09-01 14:37 UTC, herokudev commented on app/Http/Controllers/ClientesController.php
> +    public function create(Request $body)
Resolved -> OK

2023-09-01 14:39 UTC, merged

2023-09-01 14:43 UTC, CarlosAlvarado15 reviewed
LGTM