modelo personas
niver-copa/back-funval pull request #9
Opened 2023-08-31 17:47 UTC by CarlosYaelCervantesRojas

2023-08-31 19:51 UTC, herokudev requested changes

2023-08-31 19:51 UTC, herokudev commented on app/Http/Controllers/PersonaController.php
> +    public function destroy($id)
Segun lo acordado por el grupo no estamos trabajando con destroy, favor hacer los cambio necesarios para borrado logico

2023-08-31 19:51 UTC, herokudev commented on app/Http/Controllers/PersonaController.php
> +    public function store(Request $request)
Falta validacion de tipos de datos. Favor hacer los cambios necesarios

2023-09-01 00:36 UTC, CarlosYaelCervantesRojas commented on app/Http/Controllers/PersonaController.php
> +    public function store(Request $request)
Datos verificados y borrado logico

2023-09-01 14:35 UTC, herokudev approved these changes

2023-09-01 14:35 UTC, herokudev commented on app/Http/Controllers/PersonaController.php
> +    public function store(Request $request)
Resolved->OK

2023-09-01 15:07 UTC, CarlosAlvarado15 commented
Buenas Carlos, hay conflictos en las rutas, miralo por favor

2023-09-01 15:48 UTC, merged

2023-09-01 15:49 UTC, CarlosAlvarado15 reviewed
LGTM